<?php
/**
 * Created by PhpStorm.
 * User: Jne
 * Date: 2018/8/16
 * Time: 14:28
 */

namespace app\api\controller\v1;

use app\api\controller\Common;
use app\common\lib\Aes;
use app\common\lib\exception\ApiException;
use app\common\lib\Page;
use think\Controller;


/**
 * 客户端权限auth登陆基础类库
 * Class AuthBase
 * @package app\api\controller\v1
 */
class AuthBase extends Common {

    //登陆用户的基本信息
    public $user = [];
    //初始化

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if(empty($this->isLogin())){
            throw new ApiException('您没有登陆',404);
        }
    }

    //判断用户是不是登陆了

    public function isLogin(){

        if(empty($this->headers['access_user_token'])){
            return false;
        }

        $obj = new Aes();

        //解密app传过来的密钥
        $accessUserToken = $obj->decrypt($this->headers['access_user_token']);

        //如果没有直接返回false;
        if(empty($accessUserToken)){
            return false;
        }
        //正则一下没有这个也false
        if(!preg_match("/||/",$accessUserToken)){

            return false;
        }

        //加密的时候是多个||前缀加密的所以要分开，数据表里面的密钥没有这个||
        list($token,$id) = explode("||",$accessUserToken);



        $user = model('User')->get(['token'=>$token]);




        //如果查询表里面有这个token但是状态不是1也是false;
        if(!$user || $user->status != 1){

            return false;
        }

        //判断是不是时间是否是过期
        if(time() > $user->time_out){
            return false;
        }



        $this->user = $user;
        return true;

    }


}